### ISSUE TITLE
Some dependency crashes the game on load

### ISSUE THREAD

**Issue by Dragonracer1973** [Juuxel/Adorn#15] opened 2019-05-24 23:32 UTC
Hello I rlly like this mod, but upon loading this, and its dependencies into my instance I get this crash log 
[crash-2019-05-24_18.30.53-client.txt](https://github.com/Juuxel/Adorn/files/3218865/crash-2019-05-24_18.30.53-client.txt) I'm not 100% I got towellet in here, but even with it I still get a crash

**Comment by Juuxel** [comment] 2019-05-25 09:15
You have an outdated Adorn version (1.0.0, while the newest is 1.0.1). Try again with the latest version, which you can get from Curse: https://minecraft.curseforge.com/projects/adorn/files/2712391

**Comment by Dragonracer1973** [comment] 2019-05-25 11:09
updated adorn, same result 
[crash-2019-05-25_06.06.20-client.txt](https://github.com/Juuxel/Adorn/files/3219319/crash-2019-05-25_06.06.20-client.txt)

**Comment by Dragonracer1973** [comment] 2019-05-25 11:15
Updated Adorn, same result 
[crash-2019-05-25_06.14.38-client.txt](https://github.com/Juuxel/Adorn/files/3219322/crash-2019-05-25_06.14.38-client.txt)

**Comment by Dragonracer1973** [comment] 2019-05-25 11:23
tested in a stand alone pack, and I still get the same result 
[crash-2019-05-25_06.22.17-client.txt](https://github.com/Juuxel/Adorn/files/3219332/crash-2019-05-25_06.22.17-client.txt)

**Comment by Juuxel** [comment] 2019-05-27 16:06
So, this is not caused by Adorn itself but by another mod. This needs some investigation.

**Comment by Dragonracer1973** [comment] 2019-05-28 21:41
update, apparently you may wish to change the dependency tab on Curse, because you have them hard codded into the mod, essentially the crash was happening due to having duped mods of both Towelette, and Polyester

**Comment by Juuxel** [comment] 2019-05-29 04:28
Hm? They're marked as *embedded dependencies* (and I mentioned bundling in the description).

Also, that still shouldn't happen, I'll look into it some time.

**Closed** 2019-06-09 13:41 UTC
Labels: bug
