### ISSUE TITLE
crash on launch using fabric-loader-0.4.7+build.147-1.14.1+build.4 

### ISSUE THREAD

**Issue by SDUBZ** [Juuxel/Adorn#10] opened 2019-05-14 03:45 UTC
minecraft:1.14
adorn: Adorn-0.1.3+1.14

 Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
 at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
 at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
 at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
 Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: adorn requires {fabric @ [>=0.2.7]})
 at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
 at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:483)
 at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
 ... 2 more
 Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
 at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
 at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
 at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
 at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
 at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
 ... 4 more

**Comment by Juuxel** [comment] 2019-05-14 14:19
What version of Fabric API do you have?

**Comment by SDUBZ** [comment] 2019-05-14 15:13
this is the version im currently sing fabric-api-0.3.0-pre+build.156

**Comment by Juuxel** [comment] 2019-05-14 15:27
This is caused by Adorn 0.1.3 not supporting Fabric API 0.3.0 yet. This will be fixed in Adorn 0.2.0.

**Comment by SDUBZ** [comment] 2019-05-15 06:32
thank you and i love what you done so afr and thanks for the info

**Closed** 2019-05-17 15:09 UTC
Labels: bug
