### ISSUE TITLE
Modded Chests Support

### ISSUE THREAD

**Issue by zachsai** [Juuxel/Adorn#159] opened 2021-04-27 20:24 UTC
Please add crafting recipe support for the different drawer and what not with quark chests
Ex: Birch Drawer = 2 birch slabs and accepts quark:birch_chest or just the tag -> forge:chests/wooden

**Comment by Juuxel** [comment] 2021-04-28 19:54
Duplicate of #143.

**Closed as completed by Juuxel** 2021-04-28 19:54 UTC
Labels: duplicate, enhancement
