### ISSUE TITLE
Adorn Recipes Doesnt Work With Chests from Charm Mod

### ISSUE THREAD

**Issue by WolfofRoses** [Juuxel/Adorn#215] opened 2021-10-16 21:38 UTC
### Versions of Minecraft, Forge and Adorn
- Adorn: 1.16.5, Charm 1.16.5
- Minecraft: 1..16.5
- Forge: 36.20

### The Charm Mod has chests made from individual wood types, spruce chests, oak chest ect. These chests couldn't be used in any adorn furniture recipes.

Adorn crafting recipes only recognise vanilla chests in the crafting table, which means you have to specifically make a vanilla chest by mixing your wood types in the crafting table, this makes the mod experience clunker.

![image](https://user-images.githubusercontent.com/92651604/137602619-33bfa2df-16ae-4de4-966c-9d3dda019a8a.png)
Above is picture the recipe for drawers using a charmed oak chest, the recipe doesn't work because the chest is not vanilla.

### Expected behavior
You should be able to use Charm chests in Adorn crafting recipes.

**Comment by Juuxel** [comment] 2021-10-16 21:48
Duplicate of #143.

**Closed as completed by Juuxel** 2021-10-16 21:48 UTC
Labels: bug, duplicate, forge
