### ISSUE TITLE
Server crashes, can't rejoin everytime I try to it keeps crashing 

### ISSUE THREAD

**Issue by skadipooqs** [Juuxel/Adorn#147] opened 2021-03-08 19:43 UTC
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.12.2
- Minecraft: 1.16.4
- Fabric Loader: 0.11.2 
- Fabric API: 0.31.0

### Describe the bug
Not sure why, after placing a kitchen counter on top of a block (that was also from a different mod "Blockus") the game crashed with a crash log that I will attach. Weird thing is, before that I placed 6 other kitchen counters on a different position and there was no problem, until I went to the corner of the room to place one more kitchen counter and the game crashed.

### To Reproduce
1. Get in creative
2. Pick out kitchen counter
3. Place them on top of blocks from another mod (Blockus - block called "kitchen tiles" crafted from 4 black and 4 white concrete) or just on normal blocks
4. Crash

### Expected behavior
Not really sure because as I said, the kitchen counters were placed couple of times before, it was just this one time that it crashed. I expect it not to crash most of the time, but this time it did. Tried to recreate the problem in creative local server, didn't crash.

### Additional context *(Optional)*
I will add a screenshot of all the mods used during the time of the crash and the time I tested it again in local creative server (both  times it was the same mods, untouched) , and I will attach the crash log.
![mods](https://user-images.githubusercontent.com/80284509/110372576-c2dd0080-804e-11eb-97e5-b7571673448c.png)
[crash-2021-03-07_23.28.20-client.txt](https://github.com/Juuxel/Adorn/files/6103754/crash-2021-03-07_23.28.20-client.txt)

----- pastebin version of the crash log here--------
https://pastebin.com/Aks2gD8e

**Comment by skadipooqs** [comment] 2021-03-09 00:05
happened again after i backed up the world files to earlier time, but now after placing a birch kitchen sink...

**Comment by siaynoq** [comment] 2021-04-28 04:47
I think this bug is related to #139

**Comment by Juuxel** [comment] 2021-04-28 18:28
Yeah, this is a duplicate of that issue.

**Closed as completed by Juuxel** 2021-04-28 18:28 UTC
Labels: bug, duplicate
