### ISSUE TITLE
Transparent texture bug with tables

### ISSUE THREAD

**Issue by TH3N3WN00B** [Juuxel/Adorn#307] opened 2023-03-21 20:38 UTC
### Adorn version

Adorn-3.8.1+1.19.2-fabric

### Minecraft version

1.19.2

### Mod loader

Fabric

### Mod loader version

0.14.17

### Describe the bug

Tables have transparent texture being able to see thru the world

![2023-03-21_14 15 01](https://user-images.githubusercontent.com/10799738/226734599-4a25d0a6-412f-4178-9b09-528c059ebdf2.png)
![2023-03-21_14 15 05](https://user-images.githubusercontent.com/10799738/226734605-b0e3a1be-7937-4415-bd25-8ed5d2b2be83.png)

### To reproduce

Install this mod pack:

https://www.mediafire.com/file/xxkizsavx3mtfmk/mods-y-configs.rar/file

### Game logs

```text
N/A
```

### Additional context

N/A

**Comment by Juuxel** [comment] 2023-05-05 15:28
I cannot debug 500MB modpack files, please send your mod list in a more practical form. Do you have a culling mod like More Culling installed?

**Comment by sh0tybumbati** [comment] 2023-05-21 06:53
Same thing was happening to me w/ drawers- the blocks adjacent to them were being culled.
I can confirm that it was MoreCulling for me, and turning off blockstate culling fixed it:
https://i.imgur.com/Q1krtld.png
https://i.imgur.com/73PpoXW.png

**Comment by skunkmommy** [comment] 2023-05-27 14:38
I also saw this issue with counters, and turning off blockstate culling also fixes it.

**Comment by skunkmommy** [comment] 2023-05-27 14:47
It no longer happens with regular tables, but it does happen with coffee tables.

**Comment by Juuxel** [comment] 2023-06-11 16:27
MoreCulling has caused these bugs in the past, see #284.

**Comment by Juuxel** [comment] 2023-06-18 21:58
I believe this is a duplicate of #284.

**Closed as not planned by Juuxel** 2023-06-18 21:58 UTC
Labels: bug, duplicate, mod compatibility
