### ISSUE TITLE
Picket Fence issue

### ISSUE THREAD

**Issue by CharaViolet** [Juuxel/Adorn#87] opened 2020-07-25 01:46 UTC
Picket Fences seem to have issues when connecting to other fences
![2020-07-24_22 38 05](https://user-images.githubusercontent.com/28274295/88446321-70244080-cdff-11ea-960a-0626cea85a23.png)

**Comment by Juuxel** [comment] 2020-07-25 15:33
Duplicate of #58.

**Closed as completed by Juuxel** 2020-07-25 15:33 UTC
Labels: bug, duplicate
