### ISSUE TITLE
Glitch when sitting on sofas on a server

### ISSUE THREAD

**Issue by lostopkk** [Juuxel/Adorn#287] opened 2022-09-20 01:08 UTC
### Adorn version

3.6.1

### Minecraft version

1.19.2

### Mod loader

Fabric

### Mod loader version

0.14.9 0.60.0

### Describe the bug

I was on my server quietly when I put the couch and I couldn't leave and I could only move up and down, I killed myself in the game to leave but it started to give a bug every time I enter the map and my game keeps crashing

### To reproduce

1- put the couch
2- sit on it
3- problem happens

### Game logs

```text
log below
```

### Additional context

[latest.log](https://github.com/Juuxel/Adorn/files/9603217/latest.log)

Video:https://drive.google.com/file/d/1ZVr2zbFIZHJ000gpQ6NfBg1xcCfBhWbB/view?usp=sharing

**Comment by NyakoFox** [comment] 2022-10-05 01:49
I'm also experiencing this issue.

**Comment by Ryuushen** [comment] 2022-10-18 18:10
I have the same issue on server. 
https://streamable.com/z9fmmg

I have tried to install same as single player and local host but for some reason. Single player works just fine even with all the mods i had but this only happen on server. Have tried to remove all server sided mod but no help

**Comment by Juuxel** [comment] 2022-11-06 14:53
Can't reproduce with pure Adorn. Can you post your full mod list? For example Immersive Portals might cause these types of bugs.

**Comment by Ratismal** [comment] 2022-11-06 19:16
Seems to be a conflict with [VMP](https://modrinth.com/mod/vmp-fabric) [(repo)](https://github.com/RelativityMC/VMP-fabric).

Repro'd the issue running both a server and client with the following mods:
- Adorn
- fabric-api
- fabric-language-kotlin
- vmp

**Comment by Ratismal** [comment] 2022-11-06 23:04
Revisited this, I want to clarify that it's specifically the "use_optimized_entity_tracking" setting of VMP that breaks Adorn.

@lostopkk @Ryuushen @NyakoFox As a stopgap workaround for the time being, you can try disabling this property.

**Comment by shaboon** [comment] 2023-08-17 01:22
Sorry, could you explain how to disable that property?

**Comment by Juuxel** [comment] 2023-10-07 23:14
Seems to be fixed on VMP's side.

**Closed as completed by Juuxel** 2023-10-07 23:14 UTC
Labels: bug, mod compatibility, fabric
