### ISSUE TITLE
Sitting in chair/table glitch

### ISSUE THREAD

**Issue by noonononnonnoo** [Juuxel/Adorn#106] opened 2020-10-07 19:06 UTC
When clicking on a chair to sit in it, the moving arm animation plays when you click, but right before sitting the first 2 frames of the moving hand animation play continuously, and after about 2 seconds of the frames playing, you finally go into the chair/table.

**Comment by Juuxel** [comment] 2020-10-10 11:33
Do you have Immersive Portals installed?

**Comment by noonononnonnoo** [comment] 2020-10-10 14:48
Yes, I do.

**Comment by Juuxel** [comment] 2020-10-12 17:48
In that case this is a duplicate of #33.

**Closed as completed by Juuxel** 2020-10-12 17:48 UTC
Labels: bug, duplicate, mod compatibility
