### ISSUE TITLE
Crash during worldgen: valid_spawn used before it was bound

### ISSUE THREAD

**Issue by matthew-cline** [Juuxel/Adorn#69] opened 2020-04-08 05:50 UTC
### Versions of Minecraft, Fabric and Adorn (*and Kotlin*)
- Adorn: Adorn 1.8.4 for 20w14a
- Minecraft: 20w14a
- Fabric Loader: 0.7.9+build.190-20w14a
- Fabric API: 0.5.8+build.316-1.16
- Fabric Kotlin: 1.3.61+build.1

### Describe the bug
Generating a new 1.16 world with Adorn crashes pretty soon at the beginning with:

    java.lang.IllegalStateException: Tag minecraft:valid_spawn used before it was bound

Also, according to the crash report, the data packs `fabric/adorn`, `fabric/fabric-mining-levels-v0` and  `fabric/libcd` are incompatible.  [Here is the crash report](https://github.com/Juuxel/Adorn/files/4448421/crash.txt)

### Additional context
I completely deleted the `config` directory tree, so there isn't any stale config files causing the problem.

The `datapacks` and `resourcepacks` directories are completely empty.

**Comment by Juuxel** [comment] 2020-04-08 09:29
This seems to be a duplicate of [MC-177225](https://bugs.mojang.com/browse/MC-177225).

> Also, according to the crash report, the data packs `fabric/adorn`, `fabric/fabric-mining-levels-v0` and `fabric/libcd` are incompatible.

This is a Fabric API bug with their generated datapacks. It also doesn't affect anything.

**Comment by Juuxel** [comment] 2020-09-29 12:15
Shouldn't affect Adorn in 1.16.3 anymore.

**Closed as completed by Juuxel** 2020-09-29 12:15 UTC
Labels: bug
