### ISSUE TITLE
Inventory Block GUI not opening

### ISSUE THREAD

**Issue by Wolfy8198** [Juuxel/Adorn#233] opened 2021-12-22 06:56 UTC
### Versions of Minecraft, Fabric and Adorn
- Adorn: Adorn-3.0.0-rc.1+1.18-rc3-fabric.jar
- Minecraft: 1.18
- Fabric Loader: Fabric - 0.12.12
- Fabric API: fabric-api-0.44.0+1.18.jar

### Describe the bug
Inventory Block not opening (I know it's not a conflict with Hey That's Mine, because I was experiencing this before I added HTM)

### To Reproduce
1. Place down cupboard/drawers
2. Right-click cupboard/drawers

### Expected behavior
The cupboard/drawers GUI opens

### Additional context *(Optional)*
[Error](https://pastebin.com/hGBvbPki)

**Comment by Juuxel** [comment] 2021-12-22 10:05
This looks like a compatibility issue with some other mod's mixins. Could you install MixinTrace (it's on curseforge) and/or [Crafty Crashes](https://github.com/Chocohead/Crafty-Crashes)?

I'm also 90% sure I've already indirectly fixed this by reworking the screen code for the next update, but I'd like to know the cause.

**Comment by Juuxel** [comment] 2021-12-22 12:44
Also from your log, it seems to be exactly an issue with Hey That's Mine assuming that method is only called from the server (which is true in vanilla, but not with Adorn). In any case, this is fixed by my refactors for 3.1.

(For future reference, see https://github.com/QuiltServerTools/HeyThatsMine/blob/7e9e8c3dc7b56124027904d096afa17020996fab/src/main/java/com/github/fabricservertools/htm/mixin/LockableContainerMixin.java#L37-L40)

**Closed as completed by Juuxel** 2021-12-22 12:44 UTC
Labels: bug, needs more info, mod compatibility, fabric

**Comment by Wolfy8198** [comment] 2021-12-22 17:10
Neither of those seem to have a 1.18 update. I'll try removing HTM and see if that works.

**Comment by Wolfy8198** [comment] 2021-12-22 17:38
It seems you were right. That confuses me because it worked in 1.16.5, and I thought I added HTM after I experienced this, but I guess not. Thanks!
