### ISSUE TITLE
Datapack error when loading world

### ISSUE THREAD

**Issue by Ytna** [Juuxel/Adorn#161] opened 2021-05-03 12:12 UTC
### Versions of Minecraft, Forge and Adorn
- Adorn: Adorn-1.13.1+1.16.4-forge (Only forge 1.16.5 version)
- Minecraft: Sorry couldnt find it latest version of minecraft.
- Forge: 1.16.5

### Describe the bug
When starting a world works fine but if I close the game and try to enter it I can't I have around 90 mods and I removed adorn since i saw my latest log and it turned out that I can join it again. 

[latest (1).log](https://github.com/Juuxel/Adorn/files/6414684/latest.1.log)
If i need to post addition information I will I would like to play with this mod. But it seems like that mixing them doesn't work yet so im trying to sort this out.

**Comment by Juuxel** [comment] 2021-05-03 19:57
Duplicate of #137. This is caused by Thermal Expansion loading fuel values before Adorn has properly set up its own.

**Closed as completed by Juuxel** 2021-05-03 19:57 UTC
Labels: bug, duplicate, forge
