### ISSUE TITLE
No preferred tools

### ISSUE THREAD

**Issue by piemanau** [Juuxel/Adorn#212] opened 2021-10-13 21:38 UTC
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.1.5+1.17.1
- Minecraft: 1.17.1
- Fabric Loader: 0.11.6
- Fabric API: 0.40.8+1.17

### Describe the bug
A clear and concise description of what the bug is. **If your bug is a crash, attach the full game log (found in `logs/latest.log` after the game crashes.**
It takes forever to mine the stuff even though I am using the (presumably) preferred tool.

### To Reproduce
1. Go into a world
2. Try and mine a block from your mod, for example the Cobblestone Chimney
3. Notice how it take the same amount of time with and without a pickaxe

### Expected behavior
When using a pickaxe on a cobblestone chimney I would expect it to break faster than without a pickaxe

If you need it I should be able to provide and example for you (in code)

Thanks for considering,
Lime

**Comment by Juuxel** [comment] 2021-10-13 21:39
Semi-duplicate of #202. This is easy to fix, just haven't gotten around to it yet 😄

**Comment by piemanau** [comment] 2021-10-13 21:42
Woah that was a quick reply xD, thanks!

**Closed as completed** 2021-10-16 12:06 UTC
Labels: bug, fabric
