### ISSUE TITLE
Falling Through Chairs/Sofas/Benches

### ISSUE THREAD

**Issue by syvmar** [Juuxel/Adorn#320] opened 2023-07-22 04:14 UTC
### Adorn version

5.0.0

### Minecraft version

1.20.1

### Mod loader

Fabric

### Mod loader version

0.14.21

### Describe the bug

When attempting to sit on any of the seats available with Adorn, 9 times out of 10 I will fall through the block. If there is an open space 1 or 2 blocks below, I will end up there. If there are no open spaces, my character ends up most of the way into the block with just my head poking out. Using shift to dismount/spamming jump will let me get out of the one block tall area after falling through.

I do **not** use VMP nor Immersive Portals. Happens both on my private server and in a singleplayer world.

[Here is a link](https://drive.google.com/file/d/1AX4GgVrgJhRRK1SvG-M0pQO8WbFltaWz/view?usp=drive_link) to a video showcasing the issue.

### To reproduce

- Place chair/sofa/bench
- Sit down
- Fall through (most of the time)

### Additional context

Modlist:

> Adorn-5.0.0+1.20.1-fabric.jar
altorigingui-1.20.1-1.0.0.jar
appleskin-fabric-mc1.20-2.5.0.jar
ArmorPoser-fabric-1.20.1-2.0.0.jar
autofish-1.20.jar
autorun-1.20.X-0.5.0.jar
autotools-1.6-fabric-1.20.1.jar
beautify-1.0.0+fabric-1.20.jar
BetterAdvancements-Fabric-1.20.1-0.3.2.161.jar
betterfpsdist-fabric-1.20.1-2.7.jar
BetterThirdPerson-Fabric-1.20-1.9.0.jar
Boat-Item-View-Fabric-1.20.1-0.0.5.jar
borderless-mining-1.1.8+1.20.1.jar
cem-0.8.0.jar
CHAS-1.20-1.10-Fabric.jar
cloth-config-11.1.106-fabric.jar
collective-1.20.1-6.62.jar
completeconfig-2.4.1.jar
continuity-3.0.0-beta.2+1.20.jar
cooldown-coordinator-0.6.2.jar
copperhopper-0.4.0+1.20.1.jar
darkquesting-1.1.3.jar
DiagonalFences-v8.0.0-1.20.1-Fabric.jar
digs_dnd_origins-1.20.1-0.0.11.jar
dungeons-and-taverns-v2.1.3 [Fabric].jar
Durability101-fabric-1.20-0.0.4.jar
EasyAnvils-v8.0.0-1.20.1-Fabric.jar
emi-1.0.9+1.20.1+fabric.jar
emi_loot-0.6.4.1+1.20.1.jar
enchanted-vertical-slabs-1.9.jar
EnchantedToolTips-1.3.7-1.20.jar
entity_texture_features_fabric_1.20-4.4.4.jar
extraorigins-1.20-1.jar
extra_thicc_packets-1.0.jar
fabric-api-0.85.0+1.20.1.jar
fabric-language-kotlin-1.10.0+kotlin.1.9.0.jar
fabricskyboxes-0.7.1+mc1.20.jar
fallingleaves-1.15.1+1.20.1.jar
fancymenu_fabric_2.14.7-3_MC_1.20.jar
ferritecore-6.0.0-fabric.jar
files.txt
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
framework-fabric-1.20.1-0.6.7.jar
friendsandfoes-beekeeperhut-fabric-mc1.20-1.3.0.jar
friendsandfoes-fabric-mc1.20.1-1.9.2.jar
friendsandfoes-flowerymooblooms-fabric-mc1.20-1.1.0.jar
geckolib-fabric-1.20.1-4.2.1.jar
getittogetherdrops-fabric-1.20-1.3.1.jar
gpumemleakfix-fabric-1.20.1-1.6.jar
HorseExpert-v8.0.0-1.20.1-Fabric.jar
ImmediatelyFast-1.1.16+1.20.1.jar
indium-1.0.21+mc1.20.1.jar
InventoryProfilesNext-fabric-1.20-1.10.6.jar
inventorytotem-1.20.1-3.0.jar
invhud.fabric.1.20-3.4.15.jar
iris-mc1.20-1.6.4.jar
Jade-1.20-fabric-11.1.4.jar
jei-1.20.1-fabric-15.2.0.22.jar
konkrete_fabric_1.6.1_MC_1.20.jar
lazydfu-0.1.3.jar
Lexicon-1.20.x-(v.1.5.0-fabric).jar
libIPN-fabric-1.20-3.0.2.jar
lithium-fabric-mc1.20.1-0.11.2.jar
mcda-5.0.0.jar
mcdar-3.0.0.jar
mcdw-8.0.3.jar
Modlist.txt
modmenu-7.1.0.jar
MouseTweaks-fabric-mc1.20-2.25.jar
nohostilesaroundcampfire-1.20.1-5.6.jar
NoSeeNoTick-2.0.0-1.20.1.jar
omnihopper-2.1.0+1.20.jar
Origins-1.20.1-1.10.0.jar
Origins-Classes-1.20-1.7.0.jar
origins-plus-plus-2.1.1.jar
owo-lib-0.11.1+1.20.jar
Patchouli-1.20.1-81-FABRIC.jar
Pehkui-3.7.6+1.14.4-1.20.1.jar
puffish_skills-0.5.0-1.20-fabric.jar
PuzzlesLib-v8.0.7-1.20.1-Fabric.jar
ShoulderSurfing-Fabric-1.20.1-2.4.1.jar
show-me-your-skin-1.6.7+1.20.jar
SimplyHouses-1.1.4-1.20.1-fabric.jar
SkyVillages-1.0.2.1-1.20.1-fabric.jar
slabsandstairs-1.6.0.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
soundphysics-fabric-1.20.1-1.1.1.jar
spark-1.10.42-fabric.jar
starlight-1.1.2+fabric.dbc156f.jar
trade-cycling-fabric-1.20.1-1.0.5.jar
treeharvester-1.20.1-8.2.jar
trinkets-3.7.0.jar
woolcollection-fabric-1.20.1-1.0.jar
wraith-harvestscythes-2.5.6+mc1.20.jar
wraith-waystones-3.1.2+mc1.20.jar
XaerosWorldMap_1.30.6_Fabric_1.20.jar
Xaeros_Minimap_23.5.0_Fabric_1.20.jar
yet-another-config-lib-fabric-3.0.3+1.20.jar
Zoomify-2.10.0.jar

**Comment by Wionsito** [comment] 2023-08-22 19:56
The same happens to me

**Comment by Juuxel** [comment] 2023-10-08 13:11
I can't reproduce this with only Adorn and its dependencies (even in multiplayer), so I suspect this is a mod compat issue.

**Comment by ZombieKeks** [comment] 2023-10-29 10:26
i have the same problem since 1.19.2
its some mod conflict -
u also become invisible for hostile mobs after falling thru

**Comment by Juuxel** [comment] 2023-12-15 00:14
This should be fixed in 5.1.0. Please tell me if it still doesn't work in Adorn 5.1.0+ 😅

**Closed as completed by Juuxel** 2023-12-15 00:14 UTC
Labels: bug, mod compatibility, fabric
