### ISSUE TITLE
Won't place down properly in my server

### ISSUE THREAD

**Issue by wnchstrboy** [Juuxel/Adorn#74] opened 2020-05-12 19:44 UTC
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.8.4 + 1.15.2
- Minecraft: 1.15.2
- Fabric Loader: 0.5.2.40
- Fabric API: 0.10.8+build.310-1.15

### Describe the bug
Whenever I place down an item, it shows up as a table on top of a carpet. Sometimes it has water in it. This is only a problem when playing in my server, but adorn works on single player worlds. Although, the mod works for the other player on the server so it doesn't show up just for me.

### To Reproduce
1. Go to my Minecraft server
2. Place anything from adorn (except couches, I can see couches)
3. Turns into some table that I can't even open for storage

### Expected behavior
I expected it to show up how it's supposed to

**Comment by wnchstrboy** [comment] 2020-05-12 21:16
![adorn issuew](https://user-images.githubusercontent.com/65130964/81746308-dee23680-946b-11ea-9193-5ac5d90447ee.png)

**Comment by Juuxel** [comment] 2020-08-03 11:51
Do you have the same set of mods on the client and the server?

**Comment by tazz4843** [comment] 2020-09-25 18:17
Getting this bug on 1.16.3 with ~95 other mods: placing down basically anything that isn't vanilla turns into a Adorn item.

**Comment by Juuxel** [comment] 2020-09-29 12:20
@tazz4843 That sounds like a registry remapping bug. If you're on a server, make sure that the client and server have the same mods. You can also try deleting the `fabricRegistry.dat` file in the `data` directory inside a save.

**Comment by hexablend** [comment] 2021-01-05 17:32
Having the same problem in the newest version on my Server.

**Comment by Juuxel** [comment] 2021-01-06 11:52
@hexablend This is something I can't reproduce, so try using the instructions above. AFAIK, it shouldn't be caused by Adorn, but instead Adorn suffers from it.

**Comment by GeoloeG-IsT** [comment] 2021-02-16 22:08
I had the same issue and by suppressing the files in config folder, the default config of the remaining mods was enough to restore a working version.

**Comment by Juuxel** [comment] 2021-07-17 21:32
Closing this since this has just become a catch-all for all sorts of server desync issues. This shouldn't happen with up-to-date Adorn if the mod compat configuration options match between the server and the client.

If you're using Adorn 1.x: in addition to mod compat options, make sure that the `sittingOnTables` option is the same on both sides.

**Closed as completed by Juuxel** 2021-07-17 21:32 UTC
Labels: bug, fabric

**Comment by Fonezang0201** [comment] 2021-07-27 05:23
Ok, it can be use now.
