### ISSUE TITLE
trading station becomes indestructible

### ISSUE THREAD

**Issue by superon** [Juuxel/Adorn#126] opened 2021-01-15 20:37 UTC
### Versions of Minecraft, Fabric and Adorn
- Adorn-1.12.2+1.16.4
- 1.16.4
- Fabric Loader: 0.11.0
- Fabric API: 0.29.3+1.16

### Describe the bug
after server restarts the trade station becomes indestructible, that's as it appears to me and others on the same server unless i'm misunderstand ir wrongly interpreting the problem.
### To Reproduce
1. place trading station
2. restart server
3. try to harvest trading station
4. See that it can't be collected

### Expected behavior
i'd expect it to become an item that can be picked up.

### Additional context *(Optional)*
this is being used as part of a modpack, other mods included include:
fallflyinglib@1.1.0
roughlyenoughitems-api@5.8.10
dynamicsoundfilters@1.1.3+1.16.2
kubejs@1.5.4
cloth-common-events-v1@1.4.9
ezpas@1.2.3-1.16.2
step-height-entity-attribute@1.0.0
trinkets@2.6.7
fabricloader@0.11.0
crowdin-translate@1.2
leaf-decay@1.2.0-1.16.1
endermenarefriends@1.0.1-mc1.16.4-fabric
colorunchained@1.1.1-1.16.4
durability_banks@0.1.2
fabric-dimensions-v1@2.0.1+9a6c75813a
cloth-durability-bar-api-v1@1.4.9
java@8
itemflexer@1.1.3
fabric-game-rule-api-v1@1.0.5+cbe9176f3a
adventurez@1.1.5
bettercaves@1.16.2-1.0.3
fabric-api-base@0.2.0+ab87788d3a
greennightvision@1.0
goldensteak@1.0.2
yungsapi@1.16.4-Fabric-1
org_jetbrains_kotlinx_kotlinx-serialization-runtime@0.14.0
randompatches@2.1.8-fabric
waila@1.9.22
borderlessmining@1.0.6+1.16.2
org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.21
ancientgateways@1.0.2
fabric-networking-v0@0.3.1+2a4333d33a
techreborn@3.7.3+build.192
chicken_nerf@1.0.4-1+MC1.16.2-1.16.4
lapisreserve@1.0.6
modmenu@1.14.13+build.19
varied-mobs@1.0.0
cmdkeybind@1.5.2-1.16
microconfig@1.0.3
cloth-utils-v1@1.4.9
launchersmod@3.1.0
org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.21
roughlyenoughitems-runtime@5.8.10
bebooks@1.1.4
fabric-crash-report-info-v1@0.1.2+b7f9825d3a
fabricdrawer@3.2.1-20w19a
origins@0.4.6
fabric-key-binding-api-v1@1.0.1+730711c63a
staticdata@1.1.2
adorn@1.12.2+1.16.4
fabric-networking-api-v1@1.0.0+4358fbc63a
bettermineshafts@1.16.4-1.0
veinmining@0.0.3-1.16.4
org_jetbrains_annotations@20.0.0
cleardespawn@1.16.4-fabric0.25.1-1.1.1
gbfabrictools@1.3.1+1.16.4
linkedstorage@1.3.11-1.16
simplesoundmuffler@0.2.1
fabric-structure-api-v1@1.1.3+cbe9176f3a
libaddict@0.2.1
fabric-object-builder-api-v1@1.9.2+6a2618f53a
pehkui@1.6.2+1.16.3
hctm-base@3.4.0
inventory_control_tweaks@1.2.2+MC1.16.2-1.16.4
ringsofascension@1.1.1
mcdw@2.4.8
infinitywaterbucket@1.0.3.2-compat-mc1.16.4-fabric
tinytweaks@1.1.2
fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a
wolveswitharmor@1.5.2-1.16.2
strawdummy@1.4.0
reach-entity-attributes@1.0.1
fabric-lifecycle-events-v1@1.2.0+ffb68a873a
cardinal-components-util@2.7.10
fabric-loot-tables-v1@1.0.1+6a2618f53a
cloth-armor-api-v1@1.4.9
autoconfigtoml@1.0.0-fabric
minecraft@1.16.4
horsestatsvanilla@4.1.4
xpstorage@1.3+1.16.4
fabric-command-api-v1@1.0.9+6a2618f53a
jankson@3.0.1+j1.2.0
invtrashslot@1.0.2
wands@1.3.1
origins-classes@1.1.0
fabric-renderer-indigo@0.4.3+6a2618f53a
org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2
cardinal-components@2.7.10
libgui@3.2.2+1.16.3
fabric-entity-events-v1@1.0.2+8004b36d3a
xaerominimap@21.0.0
fabric-rendering-v0@1.1.1+6a2618f53a
fabric-rendering-v1@1.5.0+c26373133a
autoconfig1u@3.3.1
fabric-tag-extensions-v0@1.1.0+e77439c73a
blue_endless_jankson@1.2.0
can-i-mine-this-block@1.0.2
appleskin@1.0.11
cloth-api@1.4.9
cloth-datagen-api-v1@1.4.9
fabric-events-lifecycle-v0@0.2.0+16acbe5ba7
climbable@0.2.0
team_reborn_energy@0.1.1
tweed@3.0.0-beta.22
splash@1.2.0
fabric-keybindings-v0@0.2.0+6a2618f53a
artifice@0.13.1+1.16.2-rc1
coloredslime@1.0
healthoverlay@3.6.14
eldritch_mobs@1.5.5
reborncore@4.6.3+build.110
villagernames@1.6.0
rpgstats@3.0.4+1.16.4
controlling@1.1.2
xaeroworldmap@1.11.7
images@0.4.0+1.16.4
fiber@0.23.0-2
roughlyenoughresources@2.1.3
cardinal-components-level@2.7.10
org_jetbrains_kotlin_kotlin-stdlib@1.4.21
com_moandjiezana_toml_toml4j@0.7.2
fabric-blockrenderlayer-v1@1.1.4+6a2618f53a
herdspanic@1.0.0
fabric@0.29.3+1.16
cardinal-components-scoreboard@2.7.10
cotton-config@1.0.0-rc.7
fabric-screen-handler-api-v1@1.1.0+6a2618f53a
the_loved_ones@1.1.0+1.16.4
clipboards@1.1.0+1.16.4
redstonelantern@0.0.3
furnacedisabler@1.0
fabric-tool-attribute-api-v1@1.2.5+6a2618f53a
extraorigins@1.16.4-6
cloth-client-events-v0@1.4.9
enchant_giver@1.0.2
fabric-events-interaction-v0@0.4.1+6a2618f53a
fabric-language-kotlin@1.4.21+build.1
mousewheelie@1.6.2+mc1.16.4
cloth-config2@4.8.3
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2
fabric-resource-loader-v0@0.4.1+0d4d7e343a
chainmail@0.5.0
org_jetbrains_kotlin_kotlin-reflect@1.4.21
expandedstorage@5.6.31
ring_of_enderchest@1.0.25
clear-skies@1.5.55
cardinal-components-entity@2.7.10
fabric-commands-v0@0.2.1+cbe9176f3a
fabric-registry-sync-v0@0.7.3+be155ae23a
cardinal-components-base@2.7.10
slotlock@1.0.1-BETA
rswires@4.9.1
lightoverlay@5.5.4
fabric-mining-levels-v0@0.1.2+6a2618f53a
cpas@1.2.0+1.16.4
fabric-item-groups-v0@0.2.2+cbe9176f3a
fabric-models-v0@0.2.0+cbe9176f3a
fabric-renderer-api-v1@0.4.0+cbe9176f3a
libcd@3.0.3+1.16.3
cardinal-components-block@2.7.10
biomemakeover@1.16.4-1.2.7
cavebiomes@0.5.1
fabric-containers-v0@0.1.9+a03e98793a
tooltipfix@1.0.2-1.16
redbits@1.6.0
artifacts@2.1.0+1.16.4-fabric
cloth-dynamic-registry-api-v1@1.4.9
campanion@1.3.1+build.51
fabric-textures-v0@1.0.5+6a2618f53a
cardinal-components-item@2.7.10
com_electronwill_night-config_core@3.6.3
fabric-rendering-fluids-v1@0.1.12+6a2618f53a
qcommon-cfg-core@3.2.0
cloth-scissors-api-v1@1.4.9
cotton-logging@1.0.0-rc.4
modid@1.4
cardinal-components-chunk@2.7.10
fabric-renderer-registries-v1@2.2.0+6a2618f53a
bettereating@0.2.0
curses@1.5.1
fabric-particles-v1@0.2.3+cbe9176f3a
fabric-networking-blockentity-v0@0.2.7+a03e98793a
roughlyenoughitems-default-plugin@5.8.10
okzoomer@4.0.1+1.16.2
custom-fog@1.3.1
cloth-basic-math@0.5.1
qcommon-croco@2.1.1
static-content@1.0.1-1.16.2
amecsapi@1.1.1+mc1.16-rc1
microdurability@0.3.0+1.16.3
spinnery@3.2.1
com_electronwill_night-config_toml@3.6.3
roughlyenoughitems@5.8.10
fabric-item-api-v1@1.2.0+6a2618f53a
llamasteeds@2020.2.8
kyrptconfig@1.1.5-1.16
netherroof@1.0.0
fabric-content-registries-v0@0.2.0+e77439c73a
nha@1.0.0
cardinal-components-world@2.7.10
fabric-biome-api-v1@3.1.0+2e23b97c3a
enchantedtooltips@1.3.4-1.16
carrier@1.6.1
fabric-object-builders-v0@0.7.1+6a2618f53a
secretrooms@0.9.2+1.16.2

**Comment by Binero** [comment] 2021-03-02 19:51
Was able to reproduce this. Seems to be a duplicate of #57, which appears to be closed mistakenly.

**Comment by Binero** [comment] 2021-03-02 19:59
Turning off trading station protection does not resolve the issue.

Snippet from the config: 

```json
{
	"protectTradingStations": false
}
```

**Comment by AmyMialee** [comment] 2021-05-30 02:40
Still getting this issue, Adorn 1.13.0 for 1.16.5 Fabric.

**Comment by superon** [comment] 2021-05-30 02:48
yea, my pack has had these disabled for 5 months now bc of this :/

**Closed as completed** 2021-06-04 16:31 UTC
Labels: bug
